name: MKE Check Network
on:
  workflow_dispatch:
    inputs:
      prNumber:
        description: PR against which to this workflow
        required: false
  push:

jobs:
  terraform:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-west-1
      TF_VERSION: 0.13.4
    name: "K8s Network Conformance Testing"
    runs-on: ubuntu-latest
    steps:
      - name: Get PR Reference
        run: |
          printenv
          # check if a an input to override the reference is set
          if [[ ${INPUT_PRNUMBER} != "" ]]; then
            GIT_REF="refs/pull/${{ github.event.inputs.prNumber }}/merge"
            echo "github_ref=$GIT_REF" >> $GITHUB_ENV
            exit 0

          # PR number was not set manually
          else
            echo "no manual override: leaving Github reference unchanged."
            echo "github_ref=$GITHUB_REF" >> $GITHUB_ENV
          fi

      - name: Run git checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ env.github_ref }}
      - name: Print slug/short variables
        run: |
          echo "Github Action variables"
          echo " - github: ${{ github }}"
          echo " - github.job: ${{ github.job }}"
          echo " - github.run_number: ${{ github.run_number }}"
          echo " - github.run_id: ${{ github.run_id }}"
          echo " - github.event_name: ${{ github.event_name }}"
          echo " - github.repository: ${{ github.repository }}"
          echo " - github.ref: ${{ github.ref }}"
          echo " - github.head_ref: ${{ github.head_ref }}"
          echo " - github.base_ref: ${{ github.base_ref }}"
          echo " - github.sha: ${{ github.sha }}"
          echo " - github.event: ${{ github.event }}"
          echo " - github.event_path: ${{ github.event_path }}"
